remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Sævarður Einarsson
description: Sævarður Einarsson

show_downloads: false

github.is_project_page: false

github.is_user_page: false
